"""MiniMax-H3 story contract: the LLM writes the story, code writes structure.

Supported stages::

    t2va    Text-to-video-with-audio. No references.
    i2va    Image-to-video-with-audio. One first-frame picture, no identity.
    fl2va   First/last-frame to video. Two boundary pictures, no identity.
    l2va    Last-frame-to-video. One last-frame picture, no identity.
    ref2va  Full reference generation / editing / continuation.

Request shape (common)::

    {"stage": "t2va", "duration_seconds": 6,
     "shots": [{"what": "...", "who": "Neko", "ambient": "...",
                "music": "...", "dialogue": "..."}]}

Image references (ref2va: 1 or 3; i2va / fl2va / l2va: 1 or 2)::

    "references": [{"kind": "picture", "who": "Neko", "image": "neko.png",
                    "width": 1024, "height": 1024}]

Optional video and audio references (ref2va only, subject to the official
envelope of 9 images / 3 videos / 3 audios / 12 mixed total)::

    "videos":   [{"kind": "video", "label": "SourceA", "path": "src.mp4",
                  "duration_seconds": 6}]
    "audios":   [{"kind": "audio", "label": "Bg", "path": "bg.wav",
                  "duration_seconds": 5}]

Facts, segments, origins, dimensions, retention markers, task-type prefixes,
and the per-mode alignment preamble do not exist in this contract — they are
generated by the dialect module from the request above.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any


STAGES: tuple[str, ...] = ("t2va", "i2va", "fl2va", "l2va", "ref2va")
KEYFRAME_STAGES: frozenset[str] = frozenset({"i2va", "fl2va", "l2va"})
REFERENCE_STAGE = "ref2va"

MAX_DURATION_SECONDS = 15.0
MIN_DURATION_SECONDS = 4.0  # MiniMax H3 official manual, revision 1241
MAX_PROMPT_CHARS = 7000     # MiniMax H3 official manual, revision 1241

MAX_SHOT_FORMULA = "1 + floor((duration - 1) / 3)"
ALLOWED_REFERENCE_COUNTS_REF2VA: tuple[int, ...] = (1, 3)
ALLOWED_PICTURE_COUNTS_KEYFRAME: tuple[int, ...] = (1, 2)

OFFICIAL_INPUT_LIMITS = {
    "max_images": 9,
    "max_videos": 3,
    "max_audios": 3,
    "max_mixed_files": 12,
    "min_video_seconds": 2.0,
    "max_video_seconds": 15.0,
    "min_audio_seconds": 2.0,
    "max_audio_seconds": 15.0,
    "max_combined_video_seconds": 15.0,
    "max_combined_audio_seconds": 15.0,
    "max_image_bytes": 30 * 1024 * 1024,
    "max_video_bytes": 50 * 1024 * 1024,
    "max_audio_bytes": 15 * 1024 * 1024,
}


class OfficialEnvelopeError(ValueError):
    """Reference / video / audio set violates MiniMax H3 official limits."""


@dataclass(frozen=True)
class Shot:
    what: str
    who: str | None = None
    ambient: str | None = None
    music: str | None = None
    dialogue: str | None = None
    language: str | None = None


@dataclass(frozen=True)
class Reference:
    """An ordered picture reference.

    ``who`` carries an identity / role label and is required for ref2va
    (the dialect uses it to bind ``<Subject N>``). For keyframe stages,
    ``who`` must be absent because keyframe labels are positional, not
    identity-bearing.
    """

    who: str | None
    image: str
    width: int | None = None
    height: int | None = None


@dataclass(frozen=True)
class VideoReference:
    label: str
    path: str
    duration_seconds: float | None = None


@dataclass(frozen=True)
class AudioReference:
    label: str
    path: str
    duration_seconds: float | None = None


@dataclass(frozen=True)
class StoryRequest:
    stage: str
    duration_seconds: float
    shots: tuple[Shot, ...]
    references: tuple[Reference, ...] = ()
    videos: tuple[VideoReference, ...] = ()
    audios: tuple[AudioReference, ...] = ()


def max_shots(duration_seconds: float) -> int:
    from math import floor

    return 1 + floor((duration_seconds - 1) / 3)


def _string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise TypeError(f"{label} must be a non-empty string")
    return value.strip()


def _coerce_shot(raw: Any, index: int) -> Shot:
    label = f"shots[{index}]"
    if not isinstance(raw, dict):
        raise TypeError(f"{label} must be an object")
    unknown = sorted(set(raw) - {"what", "who", "ambient", "music", "dialogue", "language"})
    if unknown:
        raise TypeError(f"{label} has unsupported field(s): {unknown}")
    what = _string(raw.get("what"), f"{label}.what")
    who = _string(raw["who"], f"{label}.who") if raw.get("who") is not None else None
    ambient = _string(raw["ambient"], f"{label}.ambient") if raw.get("ambient") is not None else None
    music = raw.get("music")
    if music is not None and not isinstance(music, str):
        raise TypeError(
            f"{label}.music must be a string describing the score; omit it for no music"
        )
    dialogue = raw.get("dialogue")
    language = None
    if dialogue is not None:
        if isinstance(dialogue, dict):
            dialogue_text = _string(dialogue.get("text"), f"{label}.dialogue.text")
            language = _string(dialogue.get("language"), f"{label}.dialogue.language") if dialogue.get("language") is not None else None
        else:
            dialogue_text = _string(dialogue, f"{label}.dialogue")
        if "<d>" in dialogue_text or "</d>" in dialogue_text:
            raise TypeError(f"{label}.dialogue must not contain <d> markup")
        dialogue = dialogue_text
    if raw.get("language") is not None:
        language = _string(raw["language"], f"{label}.language")
    return Shot(what=what, who=who, ambient=ambient, music=music,
                dialogue=dialogue, language=language)


def _coerce_pixels(width: Any, height: Any, label: str) -> tuple[int, int]:
    if isinstance(width, bool) or not isinstance(width, int) or width <= 0:
        raise TypeError(f"{label}.width must be a positive integer")
    if isinstance(height, bool) or not isinstance(height, int) or height <= 0:
        raise TypeError(f"{label}.height must be a positive integer")
    return width, height


def _coerce_reference(raw: Any, index: int) -> Reference:
    label = f"references[{index}]"
    if not isinstance(raw, dict):
        raise TypeError(f"{label} must be an object")
    unknown = sorted(set(raw) - {"kind", "who", "image", "width", "height"})
    if unknown:
        raise TypeError(f"{label} has unsupported field(s): {unknown}")
    kind = raw.get("kind", "picture")
    if kind != "picture":
        raise TypeError(
            f"{label}.kind must be 'picture' (videos / audios use top-level fields); got {kind!r}"
        )
    who_raw = raw.get("who")
    who = _string(who_raw, f"{label}.who") if who_raw is not None else None
    image = _string(raw.get("image"), f"{label}.image")
    width_raw = raw.get("width")
    height_raw = raw.get("height")
    width: int | None
    height: int | None
    if width_raw is None and height_raw is None:
        width = None
        height = None
    else:
        width, height = _coerce_pixels(width_raw, height_raw, label)
    return Reference(who=who, image=image, width=width, height=height)


def _coerce_duration_seconds(value: Any, label: str) -> float | None:
    if value is None:
        return None
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TypeError(f"{label}.duration_seconds must be a JSON number")
    return float(value)


def _coerce_video(raw: Any, index: int) -> VideoReference:
    label = f"videos[{index}]"
    if not isinstance(raw, dict):
        raise TypeError(f"{label} must be an object")
    unknown = sorted(set(raw) - {"kind", "label", "path", "duration_seconds"})
    if unknown:
        raise TypeError(f"{label} has unsupported field(s): {unknown}")
    kind = raw.get("kind", "video")
    if kind != "video":
        raise TypeError(f"{label}.kind must be 'video'")
    plabel = _string(raw.get("label"), f"{label}.label")
    path = _string(raw.get("path"), f"{label}.path")
    duration = _coerce_duration_seconds(raw.get("duration_seconds"), label)
    if duration is not None:
        lo = OFFICIAL_INPUT_LIMITS["min_video_seconds"]
        hi = OFFICIAL_INPUT_LIMITS["max_video_seconds"]
        if not lo <= duration <= hi:
            raise OfficialEnvelopeError(
                f"{label}.duration_seconds must be within [{lo}, {hi}], got {duration}"
            )
    return VideoReference(label=plabel, path=path, duration_seconds=duration)


def _coerce_audio(raw: Any, index: int) -> AudioReference:
    label = f"audios[{index}]"
    if not isinstance(raw, dict):
        raise TypeError(f"{label} must be an object")
    unknown = sorted(set(raw) - {"kind", "label", "path", "duration_seconds"})
    if unknown:
        raise TypeError(f"{label} has unsupported field(s): {unknown}")
    kind = raw.get("kind", "audio")
    if kind != "audio":
        raise TypeError(f"{label}.kind must be 'audio'")
    plabel = _string(raw.get("label"), f"{label}.label")
    path = _string(raw.get("path"), f"{label}.path")
    duration = _coerce_duration_seconds(raw.get("duration_seconds"), label)
    if duration is not None:
        lo = OFFICIAL_INPUT_LIMITS["min_audio_seconds"]
        hi = OFFICIAL_INPUT_LIMITS["max_audio_seconds"]
        if not lo <= duration <= hi:
            raise OfficialEnvelopeError(
                f"{label}.duration_seconds must be within [{lo}, {hi}], got {duration}"
            )
    return AudioReference(label=plabel, path=path, duration_seconds=duration)


def _check_envelope(
    *,
    pictures: int,
    videos: tuple[VideoReference, ...],
    audios: tuple[AudioReference, ...],
) -> None:
    """Validate the official MiniMax H3 ref2va envelope."""
    limits = OFFICIAL_INPUT_LIMITS
    if pictures > limits["max_images"]:
        raise OfficialEnvelopeError(
            f"references exceeds the official image limit: "
            f"{pictures} > {limits['max_images']}"
        )
    if len(videos) > limits["max_videos"]:
        raise OfficialEnvelopeError(
            f"videos exceeds the official video limit: "
            f"{len(videos)} > {limits['max_videos']}"
        )
    if len(audios) > limits["max_audios"]:
        raise OfficialEnvelopeError(
            f"audios exceeds the official audio limit: "
            f"{len(audios)} > {limits['max_audios']}"
        )
    mixed_total = pictures + len(videos) + len(audios)
    if mixed_total > limits["max_mixed_files"]:
        raise OfficialEnvelopeError(
            f"mixed reference count exceeds the official limit: "
            f"{mixed_total} > {limits['max_mixed_files']}"
        )
    if audios and pictures == 0 and len(videos) == 0:
        raise OfficialEnvelopeError(
            "audio cannot be the only reference type"
        )
    if videos:
        total = sum(v.duration_seconds or 0.0 for v in videos)
        if total > limits["max_combined_video_seconds"]:
            raise OfficialEnvelopeError(
                f"combined video duration exceeds the official limit: "
                f"{total} > {limits['max_combined_video_seconds']}"
            )
    if audios:
        total = sum(a.duration_seconds or 0.0 for a in audios)
        if total > limits["max_combined_audio_seconds"]:
            raise OfficialEnvelopeError(
                f"combined audio duration exceeds the official limit: "
                f"{total} > {limits['max_combined_audio_seconds']}"
            )


def parse_request(stage: str, payload: Any) -> StoryRequest:
    if stage not in STAGES:
        raise ValueError(
            f"unknown minimax-h3-prompt stage: {stage!r}; valid: {list(STAGES)}"
        )
    if not isinstance(payload, dict):
        raise TypeError("request must be a JSON object")
    allowed = {"duration_seconds", "shots", "references", "videos", "audios"}
    unknown = sorted(set(payload) - allowed)
    if unknown:
        raise TypeError(
            f"unsupported request field(s): {unknown}; valid fields: {sorted(allowed)}"
        )
    duration = payload.get("duration_seconds")
    if isinstance(duration, bool) or not isinstance(duration, (int, float)):
        raise TypeError(f"duration_seconds must be a JSON number (got {duration!r})")
    duration = float(duration)
    if not MIN_DURATION_SECONDS <= duration <= MAX_DURATION_SECONDS:
        raise ValueError(
            f"duration_seconds must be between {MIN_DURATION_SECONDS:g} and "
            f"{MAX_DURATION_SECONDS:g} (MiniMax H3 official envelope), got {duration}"
        )
    raw_shots = payload.get("shots")
    if not isinstance(raw_shots, list) or not raw_shots:
        raise TypeError("shots must be a non-empty array")
    shots = tuple(_coerce_shot(raw, index) for index, raw in enumerate(raw_shots))
    limit = max_shots(duration)
    if len(shots) > limit:
        raise ValueError(
            f"{len(shots)} shots exceed the maximum {limit} for {duration}s "
            f"({MAX_SHOT_FORMULA})"
        )

    raw_refs = payload.get("references")
    references: tuple[Reference, ...] = ()
    if raw_refs is not None:
        if not isinstance(raw_refs, list):
            raise TypeError("references must be an array")
        references = tuple(_coerce_reference(raw, index) for index, raw in enumerate(raw_refs))

    raw_videos = payload.get("videos")
    videos: tuple[VideoReference, ...] = ()
    if raw_videos is not None:
        if not isinstance(raw_videos, list):
            raise TypeError("videos must be an array")
        videos = tuple(_coerce_video(raw, index) for index, raw in enumerate(raw_videos))

    raw_audios = payload.get("audios")
    audios: tuple[AudioReference, ...] = ()
    if raw_audios is not None:
        if not isinstance(raw_audios, list):
            raise TypeError("audios must be an array")
        audios = tuple(_coerce_audio(raw, index) for index, raw in enumerate(raw_audios))

    if stage in KEYFRAME_STAGES:
        if videos or audios:
            raise ValueError(
                f"{stage} does not accept video / audio references; route to ref2va"
            )
        if not references:
            raise ValueError(
                f"{stage} requires at least one picture reference"
            )
        if len(references) not in ALLOWED_PICTURE_COUNTS_KEYFRAME:
            wanted = " or ".join(str(n) for n in ALLOWED_PICTURE_COUNTS_KEYFRAME)
            raise ValueError(
                f"{stage} requires {wanted} picture references, got {len(references)}"
            )
        for index, ref in enumerate(references):
            if ref.who is not None:
                raise ValueError(
                    f"references[{index}].who must be absent for {stage} "
                    "(keyframe labels are positional, not identity-bearing)"
                )
    elif stage == REFERENCE_STAGE:
        if len(references) not in ALLOWED_REFERENCE_COUNTS_REF2VA:
            wanted = " or ".join(str(n) for n in ALLOWED_REFERENCE_COUNTS_REF2VA)
            raise ValueError(
                f"ref2va requires {wanted} picture references, got {len(references)}"
            )
        owners = [ref.who for ref in references]
        if any(owner is None for owner in owners):
            raise ValueError(
                "every ref2va picture reference requires a 'who' (identity / role) label"
            )
        if len(set(owners)) != len(owners):
            raise ValueError("reference 'who' values must be unique")
        for index, shot in enumerate(shots):
            if shot.who is not None and shot.who not in owners:
                raise ValueError(
                    f"shots[{index}].who {shot.who!r} does not match any reference 'who'"
                )
        _check_envelope(pictures=len(references), videos=videos, audios=audios)
    else:  # t2va
        if references or videos or audios:
            raise ValueError(
                f"{stage} takes no references; route to ref2va / i2va / fl2va / l2va"
            )

    return StoryRequest(
        stage=stage,
        duration_seconds=duration,
        shots=shots,
        references=references,
        videos=videos,
        audios=audios,
    )